name: CI Test

on:
  push:
    branches: [dev, 'release/**']
  pull_request:
    branches: [dev, 'release/**', 'feature/**']

jobs:
  functional-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

